# Generated by Django 3.2.9 on 2021-12-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=256)),
                ('is_completed', models.BooleanField()),
                ('date_field', models.DateTimeField()),
            ],
        ),
    ]
