# Generated by Django 3.2.9 on 2021-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_field',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
